WITH GROUP_TABLE AS (
    SELECT VISITED_ON
         , SUM(AMOUNT) AS 'AMOUNT'
    FROM CUSTOMER
    GROUP BY VISITED_ON
), SUM_TABLE AS (
    SELECT *
         , SUM(AMOUNT) OVER(ORDER BY VISITED_ON ASC
                            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS 'AMOUNT_SUM'
    FROM GROUP_TABLE
)

SELECT VISITED_ON
     , AMOUNT_SUM AS 'AMOUNT'
     , ROUND(AMOUNT_SUM / 7, 2) AS 'AVERAGE_AMOUNT'
FROM SUM_TABLE
WHERE VISITED_ON >= (SELECT MIN(VISITED_ON) FROM CUSTOMER) + INTERVAL 6 DAY
ORDER BY VISITED_ON ASC;