SELECT ED1.ID
FROM ECOLI_DATA AS ED1
  LEFT JOIN ECOLI_DATA AS ED2 ON ED1.PARENT_ID = ED2.ID
  LEFT JOIN ECOLI_DATA AS ED3 ON ED2.PARENT_ID = ED3.ID
WHERE ED3.ID IS NOT NULL
  AND ED3.PARENT_ID IS NULL
ORDER BY ED1.ID ASC;