SELECT DATE_FORMAT(TRANS_DATE, '%Y-%m') AS 'MONTH'
     , COUNTRY
     , COUNT(ID) AS 'TRANS_COUNT'
     , SUM(CNT) AS 'APPROVED_COUNT'
     , SUM(AMOUNT) AS 'TRANS_TOTAL_AMOUNT'
     , SUM(AMOUNT * CNT) AS 'APPROVED_TOTAL_AMOUNT'
FROM (
    SELECT *
         , IF(STATE = 'APPROVED', 1, 0) AS 'CNT'
    FROM TRANSACTIONS
) AS STATE_COUNT_TABLE
GROUP BY DATE_FORMAT(TRANS_DATE, '%Y-%m'), COUNTRY;