SELECT ID
     , SUM(CNT) AS 'CHILD_COUNT'
FROM (SELECT ED.ID
           , IF(ED2.PARENT_ID IS NULL, 0, 1) AS 'CNT'
      FROM ECOLI_DATA AS ED
        LEFT JOIN ECOLI_DATA AS ED2 ON ED.ID = ED2.PARENT_ID) AS CNT_TABLE
GROUP BY ID, CNT
ORDER BY ID ASC;