SELECT P.PRODUCT_ID
     , IF(ROUND(SUM(P.PRICE * US.UNITS) / SUM(US.UNITS), 2) IS NULL, 0, ROUND(SUM(P.PRICE * US.UNITS) / SUM(US.UNITS), 2)) AS 'AVERAGE_PRICE'
FROM PRICES AS P
  LEFT JOIN UNITSSOLD AS US ON P.PRODUCT_ID = US.PRODUCT_ID
         AND US.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
GROUP BY P.PRODUCT_ID;