SELECT AI.ANIMAL_ID
     , AI.NAME
FROM ANIMAL_INS AS AI
  INNER JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE DATEDIFF(AO.DATETIME, AI.DATETIME) >= 0
ORDER BY DATEDIFF(AO.DATETIME, AI.DATETIME) DESC
LIMIT 2;
  