SELECT DISTINCT CRCC.CAR_ID
     , CRCC.CAR_TYPE
     , FLOOR((CRCC.DAILY_FEE * (1 - CRCDP.DISCOUNT_RATE / 100)) * 30) AS 'FEE'
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
  LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
  LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
        AND CRCDP.DURATION_TYPE = '30일 이상'
WHERE CRCRH.CAR_ID NOT IN (
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE END_DATE BETWEEN '2022-11-01' AND '2022-11-30'
   OR END_DATE > '2022-11-30'
)
  AND FLOOR((CRCC.DAILY_FEE * (1 - CRCDP.DISCOUNT_RATE / 100)) * 30) >= 500000
  AND FLOOR((CRCC.DAILY_FEE * (1 - CRCDP.DISCOUNT_RATE / 100)) * 30) < 2000000
ORDER BY FEE DESC, CRCC.CAR_TYPE ASC, CRCC.CAR_ID DESC;