SELECT ID
     , IF(UPDOWN IS NULL, STUDENT, UPDOWN) AS 'STUDENT'
FROM (
    SELECT *
     , IF(ID % 2 = 1, LEAD(STUDENT) OVER(ORDER BY ID ASC), LAG(STUDENT) OVER(ORDER BY ID ASC)) AS 'UPDOWN'
    FROM SEAT
) AS CHANGE_TABLE;