SELECT NT.STUDENT_ID
     , NT.STUDENT_NAME
     , NT.SUBJECT_NAME
     , IF(E.STUDENT_ID IS NULL, 0, COUNT(*)) AS 'ATTENDED_EXAMS'
FROM (
    SELECT *
    FROM STUDENTS AS ST
    CROSS JOIN SUBJECTS AS SB
) AS NT
  LEFT JOIN EXAMINATIONS AS E ON NT.STUDENT_ID = E.STUDENT_ID
        AND NT.SUBJECT_NAME = E.SUBJECT_NAME
GROUP BY NT.STUDENT_ID, NT.STUDENT_NAME, NT.SUBJECT_NAME
ORDER BY NT.STUDENT_ID, NT.SUBJECT_NAME;