WITH TOTAL_TABLE AS (
    SELECT REQUESTER_ID
    FROM REQUESTACCEPTED
    UNION ALL
    SELECT ACCEPTER_ID
    FROM REQUESTACCEPTED
)

SELECT REQUESTER_ID AS 'ID'
     , COUNT(*) AS 'NUM'
FROM TOTAL_TABLE
GROUP BY REQUESTER_ID
ORDER BY COUNT(*) DESC
LIMIT 1;