SELECT ID
     , CASE
           WHEN PER <= 0.25 THEN 'CRITICAL'
           WHEN PER <= 0.5 THEN 'HIGH'
           WHEN PER <= 0.75 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS 'COLONY_NAME'
FROM (SELECT ID
           , SIZE_OF_COLONY
           , ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) / COUNT(*) OVER() 'PER'
      FROM ECOLI_DATA) AS PERCEN_TABLE
ORDER BY ID ASC;


