SELECT ACTIVITY_DATE AS 'DAY'
     , COUNT(DISTINCT USER_ID) AS 'ACTIVE_USERS'
FROM (
    SELECT *
    FROM ACTIVITY
    WHERE ACTIVITY_DATE BETWEEN '2019-06-28' AND '2019-07-27'
      AND ACTIVITY_TYPE IN ('OPEN_SESSION', 'END_SESSION', 'SCROLL_DOWN', 'SEND_MESSAGE')
) AS ACTIVE_TABLE
GROUP BY ACTIVITY_DATE;

# DATEDIFF('2019-07-27', '2019-06-28') <-- 30