WITH ID_TABLE AS (
    SELECT DISTINCT PRODUCT_ID
    FROM PRODUCTS
), CAL_TABLE AS (
    SELECT *
    FROM PRODUCTS AS P
    WHERE (P.PRODUCT_ID, P.CHANGE_DATE) IN (
        SELECT PRODUCT_ID
            , MAX(CHANGE_DATE) AS 'FD'
        FROM PRODUCTS
        WHERE CHANGE_DATE <= '2019-08-16'
        GROUP BY PRODUCT_ID
    )
)

SELECT IT.PRODUCT_ID
     , IF(CT.PRODUCT_ID IS NULL, 10, NEW_PRICE) AS 'PRICE'
FROM ID_TABLE AS IT
  LEFT JOIN CAL_TABLE AS CT ON IT.PRODUCT_ID = CT.PRODUCT_ID;

