WITH CT AS (
    SELECT USER_ID
         , JOINED
         , COUNT(*) OVER() AS 'CNT'
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
    # 2021년에 가입한 사람은 158명
)

SELECT YEAR(OS.SALES_DATE) AS 'YEAR'
     , MONTH(OS.SALES_DATE) AS 'MONTH'
     , COUNT(DISTINCT OS.USER_ID) AS 'PURCHASED_USERS'
     , ROUND(COUNT(DISTINCT OS.USER_ID) / CNT, 1) AS 'PUCHASED_RATIO'
FROM ONLINE_SALE AS OS
  INNER JOIN CT ON OS.USER_ID = CT.USER_ID
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
ORDER BY YEAR(OS.SALES_DATE) ASC, MONTH(OS.SALES_DATE) ASC;