SELECT MACHINE_ID
     , ROUND(SUM(DIFF) / SUM(CNT), 3) AS 'PROCESSING_TIME'
FROM (SELECT MACHINE_ID
           , PROCESS_ID
           , MAX(TIMESTAMP) - MIN(TIMESTAMP) AS 'DIFF'
           , COUNT(*) / 2 AS 'CNT'
      FROM ACTIVITY
      GROUP BY MACHINE_ID, PROCESS_ID) AS DIFF_TABLE
GROUP BY MACHINE_ID;