SELECT FO.PRODUCT_ID
     , FP.PRODUCT_NAME
     , SUM(FO.AMOUNT * FP.PRICE) AS 'TOTAL_SALES'
FROM FOOD_ORDER AS FO
  INNER JOIN FOOD_PRODUCT AS FP ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY FO.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY SUM(FO.AMOUNT * FP.PRICE) DESC, FO.PRODUCT_ID ASC;