WITH RT AS (
    -- RATE_TABLE AS RT
    SELECT *
         , DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 AS 'DIFF'
         , CASE
               WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 < 7 THEN '7일 미만'
               WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
               WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
               WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 >= 90 THEN '90일 이상'
           END AS 'RATE'
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
)

SELECT RT.HISTORY_ID
     , CASE
           WHEN CRCDP.DISCOUNT_RATE IS NOT NULL THEN RT.DIFF * (CRCC.DAILY_FEE * (1 - CRCDP.DISCOUNT_RATE / 100))
           ELSE CRCC.DAILY_FEE * RT.DIFF
       END AS 'FEE'
FROM RT
  INNER JOIN CAR_RENTAL_COMPANY_CAR AS CRCC ON RT.CAR_ID = CRCC.CAR_ID
  LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP ON RT.RATE = CRCDP.DURATION_TYPE
  AND CRCDP.CAR_TYPE = CRCC.CAR_TYPE
WHERE CRCC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, RT.HISTORY_ID DESC;