WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS 'HOUR'
    UNION ALL
    SELECT HOUR + 1 FROM HOUR_TABLE
    WHERE HOUR < 23
)

SELECT HT.HOUR
     , COUNT(ANIMAL_ID) AS 'COUNT'
FROM HOUR_TABLE AS HT
  LEFT JOIN ANIMAL_OUTS AS AO ON HT.HOUR = HOUR(AO.DATETIME)
GROUP BY HT.HOUR
ORDER BY HT.HOUR ASC;