SELECT ID
FROM (SELECT *
         , LAG(TEMPERATURE) OVER(ORDER BY RECORDDATE ASC) AS 'YESTERDAY_TEMPERATURE'
          , LAG(RECORDDATE) OVER(ORDER BY RECORDDATE ASC) AS 'YESTERDAY'
    FROM WEATHER) AS DIFF_TABLE
WHERE DATEDIFF(RECORDDATE, YESTERDAY) = 1
  AND TEMPERATURE > YESTERDAY_TEMPERATURE;