SELECT PRODUCT_ID
     , YEAR AS 'FIRST_YEAR'
     , QUANTITY
     , PRICE
FROM SALES
WHERE (YEAR, PRODUCT_ID) IN (
    SELECT MIN(YEAR)
         , PRODUCT_ID
    FROM SALES
    GROUP BY PRODUCT_ID
);