-- UNION 쓸 때는 ORDER BY 한 번만 가능
SELECT *
FROM (
    SELECT U.NAME AS 'RESULTS'
    FROM MOVIERATING AS MR
      INNER JOIN USERS AS U ON MR.USER_ID = U.USER_ID
    GROUP BY MR.USER_ID
    ORDER BY COUNT(*) DESC, U.NAME ASC
    LIMIT 1
) AS BEST_USER
UNION ALL
SELECT *
FROM (
    SELECT M.TITLE AS 'RESULTS'
    FROM MOVIERATING AS MR
      INNER JOIN MOVIES AS M ON MR.MOVIE_ID = M.MOVIE_ID
    WHERE DATE_FORMAT(CREATED_AT, '%Y-%m') = '2020-02'
    GROUP BY MR.MOVIE_ID
    ORDER BY AVG(RATING) DESC, M.TITLE ASC
    LIMIT 1
) AS BEST_MOVIE