SELECT UGU.USER_ID
     , UGU.NICKNAME
     , SUM(PRICE) AS 'TOTAL_SALES'
FROM USED_GOODS_BOARD AS UGB
  INNER JOIN USED_GOODS_USER AS UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY UGU.USER_ID
  HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE) ASC;