SELECT QUERY_NAME
     , ROUND(SUM(RATING / POSITION) / COUNT(RESULT), 2) AS QUALITY
     , ROUND(SUM(PERCEN) / COUNT(RESULT) * 100, 2) AS POOR_QUERY_PERCENTAGE
FROM (
    SELECT *
     , IF(RATING < 3, 1, 0) AS PERCEN
    FROM QUERIES
) AS PERCEN_TABLE
GROUP BY QUERY_NAME;