WITH TMP_TABLE AS (
    SELECT *
    FROM INSURANCE
    WHERE TIV_2015 IN (
        SELECT TIV_2015
        FROM INSURANCE
        GROUP BY TIV_2015
          HAVING COUNT(*) >= 2)
)

SELECT ROUND(SUM(TIV_2016), 2) AS 'TIV_2016'
FROM (
    SELECT TT.*
    FROM TMP_TABLE AS TT
      LEFT JOIN INSURANCE AS I ON TT.LAT = I.LAT AND TT.LON = I.LON
    GROUP BY TT.PID
      HAVING COUNT(*) < 2
) AS FINAL_TABLE;