WITH CNT_TABLE AS (
    SELECT MP.MEMBER_NAME
         , RR.REVIEW_TEXT
         , RR.REVIEW_DATE
         , COUNT(*) OVER(PARTITION BY RR.MEMBER_ID) AS CNT
    FROM REST_REVIEW AS RR
     INNER JOIN MEMBER_PROFILE AS MP ON RR.MEMBER_ID = MP.MEMBER_ID
    ORDER BY CNT DESC
)

SELECT MEMBER_NAME
     , REVIEW_TEXT
     , DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM CNT_TABLE
WHERE CNT = (SELECT MAX(CNT) FROM CNT_TABLE)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;