WITH MAX_CNT AS (
    SELECT MEMBER_ID
         , REVIEW_TEXT
         , REVIEW_DATE
         , COUNT(*) OVER(PARTITION BY MEMBER_ID) AS 'CNT'
    FROM REST_REVIEW
    ORDER BY CNT DESC
)

SELECT MP.MEMBER_NAME
     , RT.REVIEW_TEXT
     , DATE_FORMAT(RT.REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM (SELECT *
           , DENSE_RANK() OVER(ORDER BY CNT DESC) AS 'RNK'
      FROM MAX_CNT
) AS RT
  INNER JOIN MEMBER_PROFILE AS MP ON RT.MEMBER_ID = MP.MEMBER_ID
WHERE RT.RNK = 1
ORDER BY RT.REVIEW_DATE ASC, RT.REVIEW_TEXT ASC;
