SELECT M.EMPLOYEE_ID
     , M.NAME
     , COUNT(*) AS 'REPORTS_COUNT'
     , ROUND(AVG(E.AGE)) AS 'AVERAGE_AGE'
FROM EMPLOYEES AS M
INNER JOIN EMPLOYEES AS E ON M.EMPLOYEE_ID = E.REPORTS_TO
GROUP BY M.EMPLOYEE_ID
  HAVING COUNT(*) >= 1
ORDER BY M.EMPLOYEE_ID ASC;