WITH NDT AS (
    SELECT PLAYER_ID
         , DATE_ADD(FIRST_LOGGED_DAY, INTERVAL 1 DAY) AS 'NEXT_LOG_DAY'
    FROM (
        SELECT PLAYER_ID
             , MIN(EVENT_DATE) AS 'FIRST_LOGGED_DAY'
        FROM ACTIVITY
        GROUP BY PLAYER_ID
) AS FLDT -- FIRST_LOGGED_DAY_TABLE
)

SELECT ROUND(COUNT(A.PLAYER_ID) / COUNT(N.PLAYER_ID), 2) AS 'FRACTION'
FROM NDT AS N
LEFT JOIN ACTIVITY AS A ON N.PLAYER_ID = A.PLAYER_ID
      AND N.NEXT_LOG_DAY = A.EVENT_DATE;