SELECT DISTINCT CRH.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRH
  INNER JOIN CAR_RENTAL_COMPANY_CAR AS CRC ON CRH.CAR_ID = CRC.CAR_ID
WHERE CRC.CAR_TYPE = '세단'
  AND MONTH(START_DATE) = 10
ORDER BY CRH.CAR_ID DESC;