WITH CATEGORY_TABLE AS (
    SELECT 'Low Salary' AS 'CATEGORY'
    UNION ALL
    SELECT 'Average Salary' AS 'CATEGORY'
    UNION ALL
    SELECT 'High Salary' AS 'CATEGORY'
)

SELECT CT.CATEGORY
     , IF(ACCOUNTS_WITH_CATEGORY.CATEGORY IS NULL, 0, COUNT(*)) AS 'ACCOUNTS_COUNT'
FROM (
    SELECT *
         , CASE
             WHEN INCOME < 20000 THEN 'Low Salary'
             WHEN INCOME BETWEEN 20000 AND 50000 THEN 'Average Salary'
             WHEN INCOME > 50000 THEN 'High Salary'
           END AS 'CATEGORY'
    FROM ACCOUNTS
) AS ACCOUNTS_WITH_CATEGORY
RIGHT JOIN CATEGORY_TABLE AS CT ON ACCOUNTS_WITH_CATEGORY.CATEGORY = CT.CATEGORY
GROUP BY CT.CATEGORY;