SELECT ID
     , FISH_NAME
     , LENGTH
FROM (SELECT FI.ID
           , FI.FISH_TYPE
           , IF(FI.LENGTH IS NULL, 10, FI.LENGTH) AS 'LENGTH'
           , FNI.FISH_NAME
           , RANK() OVER(PARTITION BY FISH_NAME ORDER BY LENGTH DESC) AS 'RNK'
      FROM FISH_INFO AS FI
        INNER JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE) AS RNK_TABLE
WHERE RNK = 1
ORDER BY ID ASC;
