SELECT TGT.SCORE
     , TGT.EMP_NO
     , HE.EMP_NAME
     , HE.POSITION
     , HE.EMAIL
FROM (SELECT EMP_NO
           , SUM(SCORE) AS 'SCORE'
      FROM HR_GRADE AS HG
      GROUP BY EMP_NO) AS TGT -- TOTAL_GRADE_TABLE
  INNER JOIN HR_EMPLOYEES AS HE ON TGT.EMP_NO = HE.EMP_NO
ORDER BY TGT.SCORE DESC
LIMIT 1;