SELECT DISTINCT NUM AS 'ConsecutiveNums'
FROM (
    SELECT *
         , LAG(NUM) OVER(ORDER BY ID ASC) AS 'REAR'
         , LEAD(NUM) OVER(ORDER BY ID ASC) AS 'FRONT'
    FROM LOGS
) AS NT
WHERE NUM = REAR
  AND REAR = FRONT