WITH FRONT_END AS (
    SELECT SUM(CODE) AS 'CODE'
    FROM SKILLCODES
    GROUP BY CATEGORY
      HAVING CATEGORY = 'Front End'
), FINAL_TABLE AS (
    SELECT CASE
               WHEN (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) != 0 AND (SKILL_CODE & (SELECT CODE FROM FRONT_END)) THEN 'A'
               WHEN (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) != 0 THEN 'B'
               WHEN (SKILL_CODE & (SELECT CODE FROM FRONT_END)) !=0 THEN 'C'
               ELSE NULL
           END AS 'GRADE'
         , ID
         , EMAIL
    FROM DEVELOPERS
    ORDER BY GRADE ASC, ID ASC
)

SELECT *
FROM FINAL_TABLE
WHERE GRADE IS NOT NULL;