SELECT SU.USER_ID
     , ROUND(SUM(IF(CF.ACTION = 'TIMEOUT' OR CF.ACTION IS NULL, 0, 1)) / COUNT(*), 2) AS 'CONFIRMATION_RATE'
FROM SIGNUPS AS SU
  LEFT JOIN CONFIRMATIONS AS CF ON SU.USER_ID = CF.USER_ID
GROUP BY SU.USER_ID;
