SELECT USER_ID
     , ROUND(SUM(ACTION_NUMBER) / COUNT(*), 2) AS 'CONFIRMATION_RATE'
FROM (
    SELECT SU.USER_ID
         , CF.TIME_STAMP
         , CF.ACTION
         , CASE
             WHEN ACTION = 'TIMEOUT' OR ACTION IS NULL THEN 0
             ELSE 1
           END AS 'ACTION_NUMBER'
    FROM SIGNUPS AS SU
      LEFT JOIN CONFIRMATIONS AS CF ON SU.USER_ID = CF.USER_ID
) AS CAL_TABLE
GROUP BY USER_ID;